version: 2.1

orbs:
  orb-publisher: nmiyake/orb-publisher@dev:scratch-1

release-tags-filter: &release-tags-filter
  filters:
    tags:
      only: /.+\/v?.+/

publish-block: &publish-block
  namespace: nmiyake
  requires:
    - orb-publisher/lint
    - orb-publisher/build

workflows:
  version: 2
  main:
    jobs:
      - orb-publisher/lint:
          <<: *release-tags-filter
      - orb-publisher/build:
          <<: *release-tags-filter
      - orb-publisher/dev-publish:
          <<: *publish-block
          filters:
            branches:
              only: develop
      - orb-publisher/release-publish:
          <<: *publish-block
          filters:
            tags:
              only: /.+\/v?.+/
            branches:
              ignore: /.*/
